# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/11-RMX2195_11_C.01_210729-1627526670768-release-keys/RMX2195/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),RMX2195)

endif
